[testServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[loginServer]
BROKER_HOST = 100.80.184.27
BROKER_PORT = 5672
USER = loginUser
PASSWORD = loginPass123
VHOST = loginHost
EXCHANGE = loginExchange
QUEUE = loginQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[registerServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = registerUser
PASSWORD = registerPass123
VHOST = registerHost
EXCHANGE = registerExchange
QUEUE = registerQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[dmzServer]
BROKER_HOST = 100.80.184.27
BROKER_PORT = 5672
USER        = dmzUser
PASSWORD    = dmzPass123
VHOST       = dmzHost
EXCHANGE    = dmzExchange
QUEUE       = dmzQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
