CREATE TABLE IF NOT EXISTS sessions (
	id		INT		NOT NULL	AUTO_INCREMENT,
	user_id		INT		NOT NULL,
	session_key	CHAR(64)	NOT NULL,
	created_at	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	expires_at	TIMESTAMP	NOT NULL,

	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES users(id),
	UNIQUE(id)
);
