CREATE TABLE IF NOT EXISTS sessions (
	`id`		INT		NOT NULL	AUTO_INCREMENT,
	`userid`	INT		NOT NULL,
	`created`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`expire`	TIMESTAMP AS (TIMESTAMPADD(MINUTE, 30, `created`)) STORED,

	PRIMARY KEY (`id`),
	FOREIGN KEY (`userid`) REFERENCES users(`id`),
	UNIQUE(`id`)
);
